-- 019_platform_licensing.sql
-- Platform-operator controls: trial licensing + remote shop blocking.
--
-- Both tables are managed by the PLATFORM OPERATOR via the Supabase
-- dashboard / SQL editor — never by shop owners. Clients get read-only
-- access to their own shop's control row; the only client-reachable write
-- is the activate_license() RPC, which consumes a pre-generated key.
--
-- App behavior (client side):
--   * shop blocked          -> full-screen lock, app unusable
--   * not licensed + shop older than the trial window -> serial-entry screen
--   * licensed              -> runs indefinitely (until blocked)

-- ── License keys (10-digit serials, pre-generated by the operator) ─────────

create table license_keys (
  key        text primary key check (key ~ '^[0-9]{10}$'),
  created_at timestamptz not null default now(),
  used_by    uuid references shops(id) on delete set null,
  used_at    timestamptz
);

alter table license_keys enable row level security;
-- Deliberately NO policies: clients can neither read nor enumerate keys.
-- Only the SECURITY DEFINER RPC below and service_role touch this table.
grant select, insert, update, delete on license_keys to service_role;

-- ── Per-shop control row ────────────────────────────────────────────────────

create table shop_controls (
  shop_id        uuid primary key references shops(id) on delete cascade,
  blocked        boolean not null default false,
  blocked_reason text,
  licensed       boolean not null default false,
  licensed_at    timestamptz,
  license_key    text references license_keys(key),
  updated_at     timestamptz not null default now()
);

alter table shop_controls enable row level security;

-- The app must be able to READ its shop's control state to enforce the lock.
-- is_shop_member only covers active shop_users rows, so check shop ownership
-- separately (owners don't necessarily have a membership row). No client
-- write policies: blocking/unblocking is operator-only.
create policy "shop_controls_select" on shop_controls for select
  using (
    private.is_shop_member(shop_id)
    or exists (
      select 1 from shops s
      where s.id = shop_id and s.owner_id = auth.uid()
    )
  );

grant select on shop_controls to authenticated;
grant select, insert, update, delete on shop_controls to service_role;

-- ── Activation RPC ──────────────────────────────────────────────────────────
-- SECURITY DEFINER: runs with elevated rights so it can consume a key and
-- stamp the control row, neither of which the caller can do directly.
-- Only the shop's owner may activate. Returns true on success.

create or replace function activate_license(p_shop_id uuid, p_key text)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_found boolean;
begin
  -- caller must own the shop
  if not exists (
    select 1 from shops where id = p_shop_id and owner_id = auth.uid()
  ) then
    return false;
  end if;

  -- claim the key atomically (row lock prevents double-spend)
  update license_keys
  set used_by = p_shop_id, used_at = now()
  where key = p_key and used_by is null
  returning true into v_found;

  if v_found is not true then
    return false; -- unknown or already-used key
  end if;

  insert into shop_controls (shop_id, licensed, licensed_at, license_key, updated_at)
  values (p_shop_id, true, now(), p_key, now())
  on conflict (shop_id) do update
    set licensed    = true,
        licensed_at = now(),
        license_key = excluded.license_key,
        updated_at  = now();

  return true;
end;
$$;

revoke all on function activate_license(uuid, text) from public;
grant execute on function activate_license(uuid, text) to authenticated;
